### ISSUE TITLE
Windows failed on master

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/icu-feedstock#29]
The error was:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=157984&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=3002d0ca-d910-5264-f0e4-809a5057fac4&l=38

Investigating...

**Comment by beckermr** [comment]
@ocefpaf it says "Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge" one line before? Do we care about this error?

**Comment by beckermr** [comment]
Wait scratch that. This log is incredibly odd:

```
2020-05-07T13:13:36.3121689Z ========================== Starting Command Output ===========================
2020-05-07T13:13:36.3368227Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\f07f797b-45fe-4e0b-8f79-631f0fe3ac9b.cmd""
2020-05-07T13:13:36.5513684Z C:\Users\VSSADM~1\AppData\Local\Temp\conda-21264\conda.tmp - Access is denied.
2020-05-07T13:13:37.7227977Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:13:45.0601060Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp3gpsvfyb\\binstar.token'. Trying again in 1 seconds
2020-05-07T13:13:46.0610914Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:13:46.4171940Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:13:46.4177860Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpi_tb7x61\\binstar.token'. Trying again in 4 seconds
2020-05-07T13:13:50.4129438Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:13:50.7771784Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:13:50.7778048Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmphqj3gkt_\\binstar.token'. Trying again in 9 seconds
2020-05-07T13:13:59.7885106Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:14:00.1064275Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:14:00.1070201Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp_06cf0i8\\binstar.token'. Trying again in 16 seconds
2020-05-07T13:14:16.1094650Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:14:16.4591133Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:14:16.4598138Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpfpacgj4i\\binstar.token'. Trying again in 25 seconds
2020-05-07T13:14:41.4718398Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:14:41.8266940Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:14:41.8273325Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp72_7t39t\\binstar.token'. Trying again in 36 seconds
2020-05-07T13:15:17.8295634Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:15:18.1813049Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:15:18.1819229Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp40lami_g\\binstar.token'. Trying again in 49 seconds
2020-05-07T13:16:07.1859783Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:16:07.5261726Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:16:07.5269561Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpgojpavc9\\binstar.token'. Trying again in 64 seconds
2020-05-07T13:17:11.5390981Z Using BINSTAR_TOKEN for anaconda.org uploads to conda-forge.
2020-05-07T13:17:11.8609687Z Distribution D:\bld\win-64\icu-67.1-h33f27b4_0.tar.bz2 already exists for conda-forge
2020-05-07T13:17:11.8616541Z Failed to upload due to [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpysm5udx6\\binstar.token'. Trying again in 81 seconds
2020-05-07T13:18:32.8591419Z Traceback (most recent call last):
2020-05-07T13:18:32.8593642Z   File "C:\Miniconda\Scripts\upload_package-script.py", line 10, in <module>
2020-05-07T13:18:32.8594865Z     sys.exit(upload_package())
2020-05-07T13:18:32.8596427Z   File "C:\Miniconda\lib\site-packages\click\core.py", line 829, in __call__
2020-05-07T13:18:32.8599057Z     return self.main(*args, **kwargs)
2020-05-07T13:18:32.8599682Z   File "C:\Miniconda\lib\site-packages\click\core.py", line 782, in main
2020-05-07T13:18:32.8602864Z     rv = self.invoke(ctx)
2020-05-07T13:18:32.8617296Z   File "C:\Miniconda\lib\site-packages\click\core.py", line 1066, in invoke
2020-05-07T13:18:32.8618934Z     return ctx.invoke(self.callback, **ctx.params)
2020-05-07T13:18:32.8619615Z   File "C:\Miniconda\lib\site-packages\click\core.py", line 610, in invoke
2020-05-07T13:18:32.8620232Z     return callback(*args, **kwargs)
2020-05-07T13:18:32.8620939Z   File "C:\Miniconda\lib\site-packages\conda_forge_ci_setup\build_utils.py", line 168, in upload_package
2020-05-07T13:18:32.8621538Z     [config_file], validate=False)
2020-05-07T13:18:32.8622222Z   File "C:\Miniconda\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 229, in retry_upload_or_check
2020-05-07T13:18:32.8623233Z     raise TimeoutError("Did not manage to upload package.  Failing.")
2020-05-07T13:18:32.8623855Z TimeoutError: Did not manage to upload package.  Failing.
2020-05-07T13:18:33.0783736Z ##[error]Cmd.exe exited with code '1'.
2020-05-07T13:18:33.1247816Z ##[section]Finishing: Upload package
```

It cannot find the token and fails. Then on the next round it says the dist already exists. How did that dist get uploaded if it could not find the token?

**Comment by beckermr** [comment]
cc @CJ-Wright @scopatz

**Comment by hmaarrfk** [comment]
outdated
